updates

diff --git a/home/.config/sway/setup b/home/.config/sway/setup
--- a/home/.config/sway/setup
+++ b/home/.config/sway/setup
@@ -1,6 +1,17 @@
 #!/bin/bash
 
-echo "Listing input devices, add setup blocks in sway config for keyboard and touchpad" | tee -a ~/sway_setup_log
+log(){
+    printf "$1" | tee -a ~/sway_setup_log    
+}
+
+check(){
+    if [ "$?" != "0" ]; then
+	printf "$1 error : $?" | tee -a ~/sway_setup_log
+	exit 1
+    fi
+}
+
+log "Listing input devices, add setup blocks in sway config for keyboard and touchpad"
 
 # create empty pre-configured keyboard and touchpad sway config blocks
 
@@ -10,34 +21,36 @@ echo $'input "_id_" {\ndwt enabled\ntap enabled\nnatural_scroll enabled\nmiddle_
 # look for keyboard and touchpad input devices, add them to configuration
 
 swaymsg -t get_inputs | grep -i "identifier.*keyboard" | cut -d'"' -f 4 | while read -r line ; do
-    echo "Creating rules for keyboard $line" | tee -a ~/sway_setup_log
+    log "Creating rules for keyboard $line"
     # substitute device identifier in config_keyboard
     sed "s/_id_/$line/" config_keyboard > config_temp
+    check "sed"
     # insert resulting file into sway config
     sed -i -e '/# devices/r./config_temp' ~/.config/sway/config
+    check "sed"
 done
 
 swaymsg -t get_inputs | grep -i "identifier.*touchpad" | cut -d'"' -f 4 | while read -r line ; do
-    echo "Creating rules for touchpad $line" | tee -a ~/sway_setup_log
+    log "Creating rules for touchpad $line"
     # substitute device identifier in config_touchpad
     sed "s/_id_/$line/" config_touchpad > config_temp
+    check "sed"
     # insert resulting file into sway config
     sed -i -e '/# devices/r./config_temp' ~/.config/sway/config
+    check "sed"
 done
 
-# remove last two lines of sway config
 
-echo "Removing last two lines of sway config" >> | tee -a ~/sway_setup_log
-
+log "Removing last two lines of sway config"
 head -n -3 ~/.config/sway/config
+check "head"
 
-# remove this script
 
-echo "Removing setup script" | tee -a ~/sway_setup_log
-
+log "Removing setup script"
 rm -f ~/.config/sway/setup | tee -a ~/sway_setup_log
+check "rm"
 
-echo "Reloading sway" | tee -a ~/sway_setup_log
 
-# reload sway
+log "Reloading sway"
 swaymsg reload | tee -a ~/sway_setup_log
+check "swaymsg reload"
